import {
  parseFrontmatter,
  parseOpenAiYaml,
  readCatalogs,
  readPackageJson,
  writeJson,
  writeText,
} from "./lib.mjs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export function generateCatalog() {
  const packageJson = readPackageJson();
  const { skills, plugins } = readCatalogs();

  const enrichedSkills = skills.map((skill) => {
    const { frontmatter } = parseFrontmatter(`${skill.source}/SKILL.md`);
    const openai = parseOpenAiYaml(`${skill.source}/agents/openai.yaml`);

    return {
      name: skill.name,
      displayName: skill.displayName,
      category: skill.category,
      source: skill.source,
      targets: skill.targets,
      version: skill.version,
      summary: skill.summary,
      slug: skill.slug,
      description: frontmatter.description,
      interface: openai,
    };
  });

  const catalog = {
    name: "commentary-skills",
    version: packageJson.version,
    repository: "https://github.com/commentary-dev/commentary-skills",
    license: packageJson.license,
    skills: enrichedSkills,
    plugins,
  };

  writeJson("dist/catalog.json", catalog);
  writeText("dist/skills-index.md", renderSkillsIndex(catalog));
}

function renderSkillsIndex(catalog) {
  const lines = [
    "# Commentary Skills Index",
    "",
    "<!-- This file is generated by scripts/generate-catalog.mjs. Do not edit by hand. -->",
    "",
    `Version: ${catalog.version}`,
    "",
  ];

  for (const skill of catalog.skills) {
    lines.push(`## ${skill.displayName}`);
    lines.push("");
    lines.push(`- Name: \`${skill.name}\``);
    lines.push(`- Version: \`${skill.version}\``);
    lines.push(`- Source: \`${skill.source}\``);
    lines.push(`- Targets: ${skill.targets.map((target) => `\`${target}\``).join(", ")}`);
    lines.push("");
    lines.push(skill.summary);
    lines.push("");
  }

  return lines.join("\n");
}

if (process.argv[1] && path.basename(fileURLToPath(import.meta.url)) === path.basename(process.argv[1])) {
  generateCatalog();
}
